config/routes.rb
Vigestor::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :paginas
  

  root  'static_pages#home'
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  

end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
  has_many :content_fields, dependent: :destroy
  validates :tipo, presence: true
  validates :url, presence: true, uniqueness: { case_sensitive: false } 
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  
  def destroy
    Pagina.find(params[:id]).destroy
    flash[:success] = "Página borrada."
    redirect_to paginas_url
  end
  def new
    @pagina = Pagina.new
    @content_field = @pagina.content_fields.build
  end
  def create
    @pagina = Pagina.new(pagina_params)

    #De momento el tipo queda establecido a "prototipo inicial"
    @pagina.tipo = "prototipo inicial"

    @content_field = @pagina.content_fields.build(content_field_params)
    if(@pagina.save)
      
      flash[:success] = "La página se ha creado con éxito!"
      if(@content_field.save)
        flash[:success] = "La página y sus contenidos se han creado con éxito"
        
        redirect_to action: "index"
      else
      #Aquí entra si se crea la página pero no el contenido
      flash[:warning] = "Hubo problemas al crear el contenido"
      #Hay que borrar la página
      @pagina.destroy
      redirect_to :new_pagina
      end
    else
      #Aquí entra si no se crea la página
      flash[:warning] = "Hubo problemas al crear la página"
      redirect_to :new_pagina
    end
  end
 
  def index
     @paginas = Pagina.paginate(page: params[:page], per_page: 10)
  end
  def show
    @pagina = Pagina.find(params[:id])
    @content_fields = @pagina.content_fields
    case @pagina.tipo 
      
      when "prototipo inicial" 
        render layout: "vitutor_template_prov"
    end
  end
  def edit
    @pagina = Pagina.find(params[:id])
    @content_field = @pagina.content_fields.first
  end
  def update
    @pagina = Pagina.find(params[:id])
    @content_field = @pagina.content_fields.first
    if @pagina.update_attributes(pagina_params)
      flash[:success] = "Contenido de página actualizado"
      if @content_field.update_attributes(content_field_params)
        flash[:success] = "Página y campos de contenidos actualizados"
        redirect_to action: "index"
      else
        render 'edit'
      end
    else
      render 'edit'
    end
    #flash[:success] = "Se ejecuta el update"
    #render inline: "<% params.each do |p| %><p><%= p %></p><% end %>"
  end

  private
    def pagina_params
      params.require(:pagina).permit(:url)
    end
    def content_field_params
      params.require(:content_field).permit(:contenido, :title)
    end
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/paginas/_pagina.html.erb
<li>
  <%= link_to pagina.url , pagina %>
  &nbsp;&nbsp;&nbsp;<%= link_to "x Borrar", pagina, method: :delete,
                                     data: { confirm: "Estás seguro?" },
                                     title: pagina.url %>
  &nbsp;&nbsp;&nbsp;<%= link_to "Editar", edit_pagina_path(pagina),
                                     title: "Editar "+pagina.url %>
</li>

app/views/paginas/edit.html.erb
<% provide(:title,'Editar página '+@pagina.url) %>

<h1>Editar <%= @pagina.url %></h1>
<%= form_for @pagina, html: {class: "nifty_form"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= fields_for @content_field do |c_f| %>
    <%= c_f.label :title %>
    <%= c_f.text_area :title %>
    <%= c_f.label :contenido %>
    <%= c_f.text_area :contenido, size: "60x12", class: "ckeditor" %>
  <% end %>

  <%= f.submit "Actualizar" %>
<% end %>
<script type="text/javascript">
  // Replace the <textarea id="editor1"> with a CKEditor
  // instance, using default configuration.
  CKEDITOR.replace( 'content_field_contenido' );
</script>

app/views/paginas/index.html.erb
<% provide(:title, 'Todas las páginas') %>
<h1>Todas las páginas</h1>
<%= will_paginate @paginas %>
<ul class="paginas">
  <%= render @paginas %>
</ul>

<%= will_paginate @paginas %>
<%= link_to 'Crear nueva página', new_pagina_path, class: "btn btn-large btn-primary"%>

app/views/paginas/new.html.erb
<% provide(:title,'Crear página nueva') %>

<h1>Crear página nueva</h1>
<%= form_for @pagina, html: {class: "nifty_form"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= fields_for @content_field do |c_f| %>
    <%= c_f.label :title %>
    <%= c_f.text_area :title %>
    <%= c_f.label :contenido %>
    <%= c_f.text_area :contenido, size: "60x12", class: "ckeditor" %>
  <% end %>

  <%= f.submit "Create" %>
<% end %>
<script type="text/javascript">
  // Replace the <textarea id="editor1"> with a CKEditor
  // instance, using default configuration.
  CKEDITOR.replace( 'content_field_contenido' );
</script>

app/views/paginas/show.html.erb
<% provide(:title, @pagina.url) %>
  <div class="sombra-tit"><h2 class="r"><%= @content_fields.first.title %></h2></div><p><%= @content_fields.first.contenido %></p> 